#!/usr/bin/env python3
"""Generate the Statistics in Medicine cover letter from the analysis results.

Every figure quoted in the letter is read from ``results/results.json`` so the
letter cannot disagree with the manuscript.
"""

import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE.parent))

from icr_paper.src.results_loader import ci, load_results, num, pval

TITLE = (
    "The Information Contribution Ratio: a reproducible descriptor of endpoint "
    "informational weight in meta-analysis, and what it does and does not diagnose"
)


def build(res: dict) -> str:
    diff = res["simulation"]["difference_b_minus_a"]["i_squared"]
    negative = res["negative_control"]
    red = res["redundancy"]
    ist = res["ist"]
    meta = res["metadata"]

    lines = [
        "[Date]",
        "",
        "The Editors",
        "*Statistics in Medicine*",
        "",
        "Dear Editors,",
        "",
        f"We submit our manuscript, \"{TITLE}\", for consideration as a Research Article "
        "in *Statistics in Medicine*.",
        "",
        "### What the paper does",
        "",
        "Meta-analysis reduces each trial to one effect estimate for one endpoint, while "
        "trials differ substantially in how many variables they measure and in how the "
        "endpoint sits within that variable space. We formalise this structural feature as "
        "the Information Contribution Ratio (ICR), give an explicit estimand, and provide "
        "estimators computable from published baseline tables and from individual "
        "participant data. We then test, rather than assume, the natural hypothesis that "
        "dispersion in ICR is associated with statistical heterogeneity.",
        "",
        "### Why we think it suits the journal",
        "",
        "The contribution is methodological and largely negative, which we believe is of "
        "value to the meta-analysis literature. In a simulation study reported according to "
        "the ADEMP structure and with Monte Carlo standard errors throughout, the "
        "heterogeneous-ICR scenario did not show higher I-squared than the uniform-ICR "
        f"scenario (difference {num(diff['mean_difference'], 2)} percentage points, 95% "
        f"Monte Carlo confidence interval "
        f"{ci(diff['ci_lower'], diff['ci_upper'], 2)}), and a negative control in which ICR "
        "varied with no structural mechanism produced comparable heterogeneity "
        f"(mean I-squared {num(negative['i_squared']['mean'], 1)}%). A redundancy analysis "
        "shows that the dimension-counting estimator changes to "
        f"{num(red['icr_std_ratio_max_to_base'], 2)} times its value when near-duplicate "
        "covariates are added, while an eigenvalue-based effective-dimension version is "
        f"essentially unchanged (ratio {num(red['icr_effective_ratio_max_to_base'], 2)}).",
        "",
        "We therefore present ICR as a reproducible structural descriptor and reporting "
        "adjunct rather than as a diagnostic for whether pooling is appropriate, and we "
        "state the limits of the measure explicitly. An exploratory analysis of "
        f"{ist['summary']['n_countries']} country groups of the International Stroke Trial "
        "(open individual participant data) shows the principal-component estimators are "
        "computable and vary meaningfully; the regression-based estimator was associated "
        f"with 14-day mortality ({pval(ist['correlation_full']['p_regression'])}). Because "
        "those groups are recruitment strata of one trial and not independent studies, we "
        "report this as hypothesis-generating only.",
        "",
        "### Reproducibility",
        "",
        "Every number, table and figure in the manuscript is regenerated by a single "
        "command from public inputs: the International Stroke Trial data are downloaded by "
        "a script from the University of Edinburgh DataShare repository, and the published "
        "trial inputs are stored as comma-separated files with per-study citations. The "
        "manuscript is built by reading the generated result files, so no value is "
        "transcribed by hand; an audit script in the repository verifies this before each "
        "build. The analysis reported here was produced with Python "
        f"{meta['python_version']}, NumPy {meta['numpy_version']} and pandas "
        f"{meta['pandas_version']} at commit {meta['git_commit'][:8]}.",
        "",
        "### Declarations",
        "",
        "The manuscript is original, has not been published elsewhere and is not under "
        "consideration by another journal. The author declares no competing interests. No "
        "ethical approval was required: the analyses use publicly available de-identified "
        "data and simulated data. The abstract is within the 250-word limit, references "
        "follow the journal style in order of first appearance, tables follow the reference "
        "list, and the figures are supplied as separate files.",
        "",
        "Thank you for considering our submission.",
        "",
        "Yours sincerely,",
        "",
        "Tatsuki Onishi",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    output = BASE / "cover_letter_statistics_in_medicine.md"
    output.write_text(build(load_results()))
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
