#!/usr/bin/env python3
"""Generate the Health Services and Outcomes Research Methodology cover
letter from the analysis results.

Every figure quoted in the letter is read from ``results/results.json`` so the
letter cannot disagree with the manuscript.
"""

import re
import sys
from pathlib import Path

from docx import Document
from docx.shared import Pt

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE.parent))

from icr_paper.src.results_loader import ci, load_results, num, pval

TITLE = (
    "LINKO (Latent Information Normalization for Key Outcomes): A Framework for "
    "Evaluating the Validity of Meta-Analytic Pooling Across Heterogeneous RCT Data Structures"
)


def build(res: dict) -> str:
    diff = res["simulation"]["difference_b_minus_a"]["i_squared"]
    negative = res["negative_control"]
    red = res["redundancy"]
    ist = res["ist"]
    meta = res["metadata"]

    lines = [
        "[Date]",
        "",
        "The Editors-in-Chief",
        "*Health Services and Outcomes Research Methodology*",
        "",
        "Dear Editors-in-Chief,",
        "",
        f"We submit our manuscript, \"{TITLE}\", for consideration as an original "
        "research/methods paper in *Health Services and Outcomes Research Methodology*.",
        "",
        "### What the paper does",
        "",
        "Meta-analysis reduces each trial to one effect estimate for one endpoint, while "
        "trials differ substantially in how many variables they measure and in how the "
        "endpoint sits within that variable space. We formalise this structural feature within "
        "the Latent Information Normalization for Key Outcomes (LINKO) framework, whose core "
        "descriptor is the Information Contribution Ratio (ICR), give an explicit estimand, and "
        "provide estimators computable from published baseline tables and from individual "
        "participant data. We then test, rather than assume, the natural hypothesis that "
        "dispersion in ICR is associated with statistical heterogeneity.",
        "",
        "### Why we think it suits the journal",
        "",
        "The contribution is methodological and directly relevant to health services and "
        "outcomes research: meta-analyses of randomised trials are widely used to inform "
        "health policy and clinical practice, yet they routinely pool heterogeneous "
        "randomised controlled trials without a reproducible way to describe the structural "
        "differences in their data. The paper is largely negative, which we believe is of "
        "value to the meta-analysis and evidence-synthesis literature. In a simulation study "
        "reported according to the ADEMP structure and with Monte Carlo standard errors "
        "throughout, the heterogeneous-ICR scenario did not show higher I-squared than the "
        "uniform-ICR scenario (difference "
        f"{num(diff['mean_difference'], 2)} percentage points, 95% Monte Carlo confidence "
        f"interval {ci(diff['ci_lower'], diff['ci_upper'], 2)}), and a negative control in "
        "which ICR varied with no structural mechanism produced comparable heterogeneity "
        f"(mean I-squared {num(negative['i_squared']['mean'], 1)}%). A redundancy analysis "
        "shows that the dimension-counting estimator changes to "
        f"{num(red['icr_std_ratio_max_to_base'], 2)} times its value when near-duplicate "
        "covariates are added, while an eigenvalue-based effective-dimension version is "
        f"essentially unchanged (ratio {num(red['icr_effective_ratio_max_to_base'], 2)}).",
        "",
        "We therefore present LINKO as a framework, with ICR as a reproducible structural "
        "descriptor and reporting adjunct rather than as a diagnostic for whether pooling is "
        "appropriate, and we state the limits of the measure explicitly. An exploratory analysis of "
        f"{ist['summary']['n_countries']} country groups of the International Stroke Trial "
        "(open individual participant data) shows the principal-component estimators are "
        "computable and vary meaningfully; the regression-based estimator was associated "
        f"with 14-day mortality ({pval(ist['correlation_full']['p_regression'])}). Because "
        "those groups are recruitment strata of one trial and not independent studies, we "
        "report this as hypothesis-generating only.",
        "",
        "### Reproducibility",
        "",
        "Every number, table and figure in the manuscript is regenerated by a single "
        "command from public inputs: the International Stroke Trial data are downloaded by "
        "a script from the University of Edinburgh DataShare repository, and the published "
        "trial inputs are stored as comma-separated files with per-study citations. The "
        "manuscript is built by reading the generated result files, so no value is "
        "transcribed by hand; an audit script in the repository verifies this before each "
        "build. The analysis reported here was produced with Python "
        f"{meta['python_version']}, NumPy {meta['numpy_version']} and pandas "
        f"{meta['pandas_version']} at commit {meta['git_commit'][:8]}.",
        "",
        "### Declarations",
        "",
        "The manuscript is original, has not been published elsewhere and is not under "
        "consideration by another journal. The author declares no competing interests. No "
        "funding was received for this study. No ethical approval was required: the analyses "
        "use publicly available de-identified data and simulated data. The abstract is "
        "within the 250-word limit, references follow the journal's author-year style, "
        "tables are embedded in the manuscript, and figures are embedded in the manuscript "
        "and also supplied as separate high-resolution files.",
        "",
        "Thank you for considering our submission.",
        "",
        "Yours sincerely,",
        "",
        "Tatsuki Onishi",
    ]
    return "\n".join(lines) + "\n"


def _parse_italic(paragraph, text: str) -> None:
    """Add text to paragraph, italicising segments wrapped in single asterisks."""
    parts = re.split(r'(\*[^*]+\*)', text)
    for part in parts:
        run = paragraph.add_run()
        run.text = part.strip('*')
        if part.startswith('*') and part.endswith('*'):
            run.italic = True


def write_docx(text: str, output: Path, font: str = "Times New Roman") -> Path:
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = font
    style.font.size = Pt(11)
    for line in text.splitlines():
        if not line.strip():
            continue
        if line.startswith('### '):
            p = doc.add_heading(line[4:], level=3)
        else:
            p = doc.add_paragraph()
            _parse_italic(p, line)
    doc.save(str(output))
    return output


def main() -> None:
    text = build(load_results())
    md = BASE / "cover_letter_health_services_outcomes_research_methodology.md"
    md.write_text(text)
    print(f"Wrote {md}")
    docx = BASE / "cover_letter_health_services_outcomes_research_methodology.docx"
    write_docx(text, docx)
    print(f"Wrote {docx}")


if __name__ == "__main__":
    main()
